/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1_tylercruz_progra2;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tyler C
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        HiloHora h=new HiloHora(jl_hora);
        Thread proceso1 = new Thread(h);
        proceso1.start(); 
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sex = new javax.swing.ButtonGroup();
        EstadoCivil = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ComboBox_Contactos = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        RadioB_M = new javax.swing.JRadioButton();
        RadioB_F = new javax.swing.JRadioButton();
        label_Person_ID = new javax.swing.JTextField();
        label_Person_Nombre = new javax.swing.JTextField();
        label_Articulos_Titulo = new javax.swing.JTextField();
        label_Articulos_Descripcion = new javax.swing.JTextField();
        label_Articulos_Editorial = new javax.swing.JTextField();
        label_Articulos_Tamano = new javax.swing.JTextField();
        label_Articulos_Puntuacion = new javax.swing.JTextField();
        label_Person_Ocupacion = new javax.swing.JTextField();
        RadioB_Soltero = new javax.swing.JRadioButton();
        RadioB_Casado = new javax.swing.JRadioButton();
        RadioB_Divorciado = new javax.swing.JRadioButton();
        label_Person_Horario = new javax.swing.JTextField();
        label_Person_Tiempo = new javax.swing.JTextField();
        label_Articulos_Edicion = new javax.swing.JTextField();
        label_Articulos_CasaColaboracion = new javax.swing.JTextField();
        label_Articulos_Pais = new javax.swing.JTextField();
        label_Articulos_DescripcionFiguras = new javax.swing.JTextField();
        label_Articulos_InstruccionesF = new javax.swing.JTextField();
        label_Articulos_TiempoGarantia = new javax.swing.JTextField();
        label_Articulos_Volumen = new javax.swing.JTextField();
        label_Articulos_DescripcionComics = new javax.swing.JTextField();
        label_Person_Cargo = new javax.swing.JTextField();
        label_Person_Usuario = new javax.swing.JTextField();
        Button_CrearGerente = new javax.swing.JButton();
        Button_CrearPersonal = new javax.swing.JButton();
        Button_CrearComic = new javax.swing.JButton();
        Button_CrearJuego = new javax.swing.JButton();
        Button_CrearFigura = new javax.swing.JButton();
        label_Person_Edad = new javax.swing.JFormattedTextField();
        label_Person_Altura = new javax.swing.JFormattedTextField();
        label_Person_Peso = new javax.swing.JFormattedTextField();
        label_Articulos_Calidad = new javax.swing.JFormattedTextField();
        jLabel36 = new javax.swing.JLabel();
        label_Person_Password = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        label_Person_Sueldo = new javax.swing.JTextField();
        Button_Color = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_EmuladorMensaje = new javax.swing.JTable();
        jLabel40 = new javax.swing.JLabel();
        EM_Emisor = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        EM_Receptor = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        EM_Mensaje = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Message_ProgressBar = new javax.swing.JProgressBar();
        jl_hora = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_Person = new javax.swing.JTable();
        RM_ComboBox_Contactos = new javax.swing.JComboBox<>();
        RM_ComboBox_Articulos = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTable_Articulos = new javax.swing.JTable();
        RM_Button_RemovePerson = new javax.swing.JButton();
        RM_Button_ModificarPersona = new javax.swing.JButton();
        RM_Button_RemoveArticulo = new javax.swing.JButton();
        JB_ModificarArticulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Identificacion: ");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Sexo:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Edad:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Altura:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Estado Civil:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Cargo:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Peso:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Usuario:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Crear Personas");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Crear Articulos");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Titulo:");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Color:");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Descripcion:");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Editorial:");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Tamaño:");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Puntuacion: ");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("Registro: ");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("Gerente");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("Personal General");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setText("Ocupacion: ");

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setText("Horario:");

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setText("Tiempo Trabajando(Semanas): ");

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setText("Comics");

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setText("Volumen:");

        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setText("Descripcion: ");

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setText("Estado Calidad (1-10): ");

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setText("Juegos");

        jLabel29.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel29.setText("Edicion:");

        jLabel30.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel30.setText("Casa Elaboracion:");

        jLabel31.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel31.setText("Pais:");

        jLabel32.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel32.setText("Figuras");

        jLabel33.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel33.setText("Descripcion:");

        jLabel34.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel34.setText("Instruciones:");

        jLabel35.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel35.setText("Tiempo Garantia");

        Sex.add(RadioB_M);
        RadioB_M.setSelected(true);
        RadioB_M.setText("M");

        Sex.add(RadioB_F);
        RadioB_F.setText("F");

        label_Person_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_Person_IDActionPerformed(evt);
            }
        });

        label_Person_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_Person_NombreActionPerformed(evt);
            }
        });

        label_Articulos_Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_Articulos_TituloActionPerformed(evt);
            }
        });

        EstadoCivil.add(RadioB_Soltero);
        RadioB_Soltero.setSelected(true);
        RadioB_Soltero.setText("Soltero");

        EstadoCivil.add(RadioB_Casado);
        RadioB_Casado.setText("Casado");

        EstadoCivil.add(RadioB_Divorciado);
        RadioB_Divorciado.setText("Divorciado");

        label_Articulos_CasaColaboracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_Articulos_CasaColaboracionActionPerformed(evt);
            }
        });

        label_Articulos_DescripcionFiguras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_Articulos_DescripcionFigurasActionPerformed(evt);
            }
        });

        label_Articulos_InstruccionesF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_Articulos_InstruccionesFActionPerformed(evt);
            }
        });

        Button_CrearGerente.setText("Create Gerente");
        Button_CrearGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CrearGerenteActionPerformed(evt);
            }
        });

        Button_CrearPersonal.setText("Create Personal");
        Button_CrearPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CrearPersonalActionPerformed(evt);
            }
        });

        Button_CrearComic.setText("Create Comics");
        Button_CrearComic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CrearComicActionPerformed(evt);
            }
        });

        Button_CrearJuego.setText("Create  Juegos");
        Button_CrearJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CrearJuegoActionPerformed(evt);
            }
        });

        Button_CrearFigura.setText("Create  Figuras");
        Button_CrearFigura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CrearFiguraActionPerformed(evt);
            }
        });

        label_Person_Edad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        label_Person_Altura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        label_Person_Peso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        jLabel36.setText("Contrasena");

        jLabel37.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel37.setText("Sueldo:");

        label_Person_Sueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_Person_SueldoActionPerformed(evt);
            }
        });

        Button_Color.setText("Color");
        Button_Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(label_Person_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_Person_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_Articulos_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBox_Contactos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_Articulos_Puntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_Articulos_Tamano, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_Articulos_Editorial, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_Color))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_Person_Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioB_M)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioB_F))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_Person_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_Person_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_Articulos_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(82, 82, 82)
                                                .addComponent(label_Person_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(122, 122, 122)
                                                .addComponent(label_Person_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel25)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(label_Articulos_Volumen, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(label_Person_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(label_Articulos_DescripcionComics, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label_Person_Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label_Articulos_Edicion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label_Person_Ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label_Person_Horario, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label_Articulos_Pais, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label_Articulos_CasaColaboracion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label_Person_Sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label_Articulos_InstruccionesF))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label_Articulos_DescripcionFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label_Articulos_TiempoGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Button_CrearComic)
                                            .addComponent(Button_CrearGerente))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Button_CrearPersonal)
                                            .addComponent(Button_CrearJuego)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Button_CrearFigura)
                                        .addGap(67, 67, 67))))
                            .addComponent(label_Articulos_Calidad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioB_Soltero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioB_Casado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioB_Divorciado))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel27)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel21)
                    .addComponent(label_Person_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Person_Ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Person_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel22)
                    .addComponent(label_Person_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Person_Horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Person_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel23)
                        .addComponent(label_Person_Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_Person_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_Person_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RadioB_M)
                    .addComponent(RadioB_F)
                    .addComponent(jLabel37)
                    .addComponent(label_Person_Sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(RadioB_Soltero)
                    .addComponent(RadioB_Casado)
                    .addComponent(RadioB_Divorciado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(label_Person_Altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(label_Person_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel24)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel25)
                    .addComponent(jLabel29)
                    .addComponent(label_Articulos_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Articulos_Edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Articulos_Volumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel26)
                    .addComponent(jLabel30)
                    .addComponent(label_Articulos_CasaColaboracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Articulos_DescripcionComics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Color))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel27)
                    .addComponent(jLabel31)
                    .addComponent(label_Articulos_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Articulos_Pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(label_Articulos_Editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Articulos_Calidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(label_Articulos_Tamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel32)
                    .addComponent(label_Articulos_Puntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_CrearGerente)
                    .addComponent(Button_CrearPersonal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(ComboBox_Contactos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(label_Articulos_DescripcionFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_CrearComic)
                    .addComponent(Button_CrearJuego))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel34)
                            .addComponent(label_Articulos_InstruccionesF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(label_Articulos_TiempoGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Button_CrearFigura))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create", jPanel2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        Table_EmuladorMensaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receptor", "Emisor", "Mensaje"
            }
        ));
        jScrollPane2.setViewportView(Table_EmuladorMensaje);

        jLabel40.setText("Emisor: ");

        jLabel41.setText("Receptor: ");

        jLabel42.setText("Mensaje: ");

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EM_Emisor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EM_Receptor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EM_Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Message_ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(EM_Emisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(EM_Receptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(EM_Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jl_hora))
                .addGap(18, 18, 18)
                .addComponent(Message_ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 209, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Emulador Mensaje", jPanel4);

        JTable_Person.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Sexo", "Usuario", "Estado Civil"
            }
        ));
        jScrollPane1.setViewportView(JTable_Person);

        RM_ComboBox_Contactos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RM_ComboBox_ContactosItemStateChanged(evt);
            }
        });
        RM_ComboBox_Contactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RM_ComboBox_ContactosActionPerformed(evt);
            }
        });

        RM_ComboBox_Articulos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RM_ComboBox_ArticulosItemStateChanged(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel38.setText("Combox de Personas: ");

        jLabel39.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel39.setText("Combox de Articulos: ");

        JTable_Articulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Descripcion", "Editorial", "Puntuacion"
            }
        ));
        jScrollPane3.setViewportView(JTable_Articulos);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RM_ComboBox_Contactos, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RM_ComboBox_Articulos, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 184, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RM_ComboBox_Contactos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RM_ComboBox_Articulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        RM_Button_RemovePerson.setText("Remove Persona");
        RM_Button_RemovePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RM_Button_RemovePersonActionPerformed(evt);
            }
        });

        RM_Button_ModificarPersona.setText("Modificar Persona");
        RM_Button_ModificarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RM_Button_ModificarPersonaActionPerformed(evt);
            }
        });

        RM_Button_RemoveArticulo.setText("Remove Articulo");
        RM_Button_RemoveArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RM_Button_RemoveArticuloActionPerformed(evt);
            }
        });

        JB_ModificarArticulo.setText("Modificar Articulo");
        JB_ModificarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ModificarArticuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(RM_Button_RemovePerson)
                                .addGap(18, 18, 18)
                                .addComponent(RM_Button_ModificarPersona))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(RM_Button_RemoveArticulo)
                                .addGap(18, 18, 18)
                                .addComponent(JB_ModificarArticulo)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RM_Button_RemovePerson)
                    .addComponent(RM_Button_ModificarPersona))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RM_Button_RemoveArticulo)
                    .addComponent(JB_ModificarArticulo))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Remove and Modify", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RM_Button_RemoveArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RM_Button_RemoveArticuloActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo
                        = (DefaultTableModel) this.JTable_Person.getModel();
        try {
            if (this.JTable_Person.getSelectedRow() >= 0) {
                this.JTable_Person.remove(this.JTable_Person.getSelectedRow());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se puedo Hacer");
        }
        JTable_Person.setModel(modelo);
    }//GEN-LAST:event_RM_Button_RemoveArticuloActionPerformed

    private void RM_Button_RemovePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RM_Button_RemovePersonActionPerformed
        // TODO add your handling code here:
        //if (this.RM_ComboBox_Contactos.getSelectedItem >= 0) {
         DefaultTableModel modelo
                        = (DefaultTableModel) this.JTable_Articulos.getModel();
        try {
            if (this.JTable_Articulos.getSelectedRow() >= 0) {
                this.JTable_Articulos.remove(this.JTable_Articulos.getSelectedRow());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se puedo Hacer");
        }
        JTable_Articulos.setModel(modelo);
        //this.RM_ComboBox_Contactos.setModel(modelo);
        //}
    }//GEN-LAST:event_RM_Button_RemovePersonActionPerformed

    private void RM_ComboBox_ContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RM_ComboBox_ContactosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RM_ComboBox_ContactosActionPerformed

    private void RM_ComboBox_ContactosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RM_ComboBox_ContactosItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == 2) {
            if (this.RM_ComboBox_Contactos.getSelectedItem() instanceof Gerente) {
                Gerente manager = (Gerente) this.RM_ComboBox_Contactos.getSelectedItem();
                Object[] newrow = {
                    manager.getID(),
                    manager.getAltura(),
                    manager.getCargo(),
                    manager.getEdad(),
                    manager.getEstadoCivil(),
                    manager.getName(),
                    manager.getSexo(),
                    manager.getPeso(),
                    manager.getContrasena(),
                    manager.getUsuario(),};
                DefaultTableModel modelo
                        = (DefaultTableModel) this.JTable_Person.getModel();
                modelo.addRow(newrow);
                this.JTable_Person.setModel(modelo);
            }
            if (this.RM_ComboBox_Contactos.getSelectedItem() instanceof Personal) {
                //String ocupacion, String Horario, int semanas, double sueldo, String ID, String name, 
                //int edad, String sexo, String estadoCivil, double altura, int peso
                Personal manager = (Personal) this.RM_ComboBox_Contactos.getSelectedItem();
                Object[] newrow = {
                    manager.getHorario(),
                    manager.getSueldo(),
                    manager.getSemanas(),
                    manager.getID(),
                    manager.getAltura(),
                    manager.getEdad(),
                    manager.getEstadoCivil(),
                    manager.getName(),
                    manager.getSexo(),
                    manager.getPeso(),};
                DefaultTableModel modelo
                        = (DefaultTableModel) this.JTable_Person.getModel();
                modelo.addRow(newrow);
                this.JTable_Person.setModel(modelo);
            }
        }
    }//GEN-LAST:event_RM_ComboBox_ContactosItemStateChanged

    private void Button_ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ColorActionPerformed
        // TODO add your handling code here:
        Button_Color.setForeground(JColorChooser.showDialog(this, "Eliga el color: ", Color.yellow));
        color = Button_Color.getForeground();
    }//GEN-LAST:event_Button_ColorActionPerformed

    private void label_Person_SueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_Person_SueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_Person_SueldoActionPerformed

    private void Button_CrearFiguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CrearFiguraActionPerformed
        // TODO add your handling code here:
        //String descriptionFig, String instructions, String garantia, String titulo, Color color, String descripcion, String editorial,
        //int tamano, int puntuacion, Person person
        try {
            int tamano, puntuacion;
            tamano = Integer.parseInt(this.label_Articulos_Tamano.getText());
            puntuacion = Integer.parseInt(this.label_Articulos_Puntuacion.getText());

            Figura x = new Figura(this.label_Articulos_DescripcionFiguras.getText(), this.label_Articulos_InstruccionesF.getText(), this.label_Articulos_TiempoGarantia.getText(),
                    this.label_Articulos_Titulo.getText(), color, this.label_Articulos_Descripcion.getText(), this.label_Articulos_Editorial.getText(), tamano, puntuacion,
                    (Person) this.ComboBox_Contactos.getSelectedItem());
            DefaultComboBoxModel dc
                    = (DefaultComboBoxModel) this.RM_ComboBox_Articulos.getModel();
            dc.addElement(x);

            JOptionPane.showMessageDialog(null, "Figura fue creado exitosamente!");
            this.label_Articulos_Volumen.setText("");
            this.label_Articulos_Calidad.setText("");
            this.label_Articulos_Tamano.setText("");
            this.label_Articulos_Puntuacion.setText("");
            this.label_Articulos_DescripcionComics.setText("");
            this.label_Articulos_Titulo.setText("");
            this.label_Articulos_Descripcion.setText("");
            this.label_Articulos_Editorial.setText("");
            this.label_Articulos_InstruccionesF.setText("");
            this.label_Articulos_TiempoGarantia.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error probablemente con los ingresos de datos");
        }
    }//GEN-LAST:event_Button_CrearFiguraActionPerformed

    private void Button_CrearJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CrearJuegoActionPerformed
        // TODO add your handling code here:
        //int edicion, String casaElaboracion, String pais, String titulo, Color color,
        //String descripcion, String editorial, int tamano, int puntuacion, Person person
        try {
            int edicion, tamano, puntuacion;
            edicion = Integer.parseInt(this.label_Articulos_Edicion.getText());
            tamano = Integer.parseInt(this.label_Articulos_Tamano.getText());
            puntuacion = Integer.parseInt(this.label_Articulos_Puntuacion.getText());
            //        articulos.add(new Juego(edicion,this.label_Articulos_CasaColaboracion.getText(),this.label_Articulos_Pais.getText(),this.label_Articulos_Titulo.getText(),
            //        color,this.label_Articulos_Descripcion.getText(),this.label_Articulos_Editorial.getText(),tamano,puntuacion,(Person)this.ComboBox_Contactos.getSelectedItem()));

            Juego x = new Juego(edicion, this.label_Articulos_CasaColaboracion.getText(), this.label_Articulos_Pais.getText(), this.label_Articulos_Titulo.getText(),
                    color, this.label_Articulos_Descripcion.getText(), this.label_Articulos_Editorial.getText(), tamano, puntuacion, (Person) this.ComboBox_Contactos.getSelectedItem());
            DefaultComboBoxModel dc
                    = (DefaultComboBoxModel) this.RM_ComboBox_Articulos.getModel();
            dc.addElement(x);

            JOptionPane.showMessageDialog(null, "Juego fue creado exitosamente!");
            this.label_Articulos_Volumen.setText("");
            this.label_Articulos_Calidad.setText("");
            this.label_Articulos_Tamano.setText("");
            this.label_Articulos_Puntuacion.setText("");
            this.label_Articulos_DescripcionComics.setText("");
            this.label_Articulos_Titulo.setText("");
            this.label_Articulos_Descripcion.setText("");
            this.label_Articulos_Editorial.setText("");
            this.label_Articulos_Editorial.setText("");
            this.label_Articulos_Pais.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error probablemente con los ingresos de datos");
        }
    }//GEN-LAST:event_Button_CrearJuegoActionPerformed

    private void Button_CrearComicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CrearComicActionPerformed
        // TODO add your handling code here:
        //double volumen, String descripcionComic, int estadoCalidad, String titulo, Color color,
        //String descripcion, String editorial, int tamano, int puntuacion, Person person
        try {
            double volumen;
            int estadoCalidad, tamano, puntuacion;
            volumen = Double.parseDouble(this.label_Articulos_Volumen.getText());
            estadoCalidad = Integer.parseInt(this.label_Articulos_Calidad.getText());
            tamano = Integer.parseInt(this.label_Articulos_Tamano.getText());
            puntuacion = Integer.parseInt(this.label_Articulos_Puntuacion.getText());
            //        articulos.add(new Comic(volumen,this.label_Articulos_DescripcionComics.getText(),estadoCalidad,this.label_Articulos_Titulo.getText(),
            //        color,this.label_Articulos_Descripcion.getText(),this.label_Articulos_Editorial.getText(),tamano,puntuacion,(Person)this.ComboBox_Contactos.getSelectedItem()));
            //
            Comic x = new Comic(volumen, this.label_Articulos_DescripcionComics.getText(), estadoCalidad, this.label_Articulos_Titulo.getText(),
                    color, this.label_Articulos_Descripcion.getText(), this.label_Articulos_Editorial.getText(), tamano, puntuacion, (Person) this.ComboBox_Contactos.getSelectedItem());
            DefaultComboBoxModel dc
                    = (DefaultComboBoxModel) this.RM_ComboBox_Articulos.getModel();
            dc.addElement(x);

            JOptionPane.showMessageDialog(null, "Comic fue creado exitosamente!");
            this.label_Articulos_Volumen.setText("");
            this.label_Articulos_Calidad.setText("");
            this.label_Articulos_Tamano.setText("");
            this.label_Articulos_Puntuacion.setText("");
            this.label_Articulos_DescripcionComics.setText("");
            this.label_Articulos_Titulo.setText("");
            this.label_Articulos_Descripcion.setText("");
            this.label_Articulos_Editorial.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error probablemente con los ingresos de datos");
        }
    }//GEN-LAST:event_Button_CrearComicActionPerformed

    private void Button_CrearPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CrearPersonalActionPerformed
        // TODO add your handling code here:
        //String ocupacion, String Horario, int semanas, double sueldo, String ID, String name, int edad, String sexo, String estadoCivil, double altura, int peso
        try {
            int edad, peso, semanas;
            double altura, sueldo;
            String sexo = "";
            String estado = "";
            edad = Integer.parseInt(this.label_Person_Altura.getText());
            semanas = Integer.parseInt(this.label_Person_Tiempo.getText());
            peso = Integer.parseInt(this.label_Person_Peso.getText());
            altura = Double.parseDouble(this.label_Person_Altura.getText());
            sueldo = Double.parseDouble(this.label_Person_Sueldo.getText());

            if (this.RadioB_M.isSelected()) {
                sexo = "Masculino";
            } else {
                sexo = "Femenino";
            }
            if (this.RadioB_Casado.isSelected()) {
                estado = "Soltero";
            } else if (this.RadioB_Divorciado.isSelected()) {
                estado = "Divorciado";
            } else if (RadioB_Casado.isSelected()) {
                estado = "Casado";
            }
            Personal x = new Personal(this.label_Person_Ocupacion.getText(), this.label_Person_Horario.getText(),
                    semanas, sueldo, this.label_Person_ID.getText(), this.label_Person_Nombre.getText(),
                    edad, sexo, estado, altura, peso);
            //        contactos.add(new Personal(this.label_Person_Ocupacion.getText(), this.label_Person_Horario.getText(),
            //                semanas, sueldo, this.label_Person_ID.getText(), this.label_Person_Nombre.getText(),
            //                edad, sexo, estado, altura, peso));
            contactos.add(x);
            DefaultComboBoxModel dc
                    = (DefaultComboBoxModel) this.ComboBox_Contactos.getModel();
            dc.addElement(x);
            DefaultComboBoxModel dc1
                    = (DefaultComboBoxModel) this.RM_ComboBox_Contactos.getModel();
            dc1.addElement(x);

            this.label_Person_Altura.setText("");
            this.label_Person_Horario.setText("");
            this.label_Person_Peso.setText("");
            this.label_Person_Altura.setText("");
            this.label_Person_Sueldo.setText("");
            this.label_Person_Ocupacion.setText("");
            this.label_Person_Horario.setText("");
            this.label_Person_ID.setText("");
            this.label_Person_Nombre.setText("");
            JOptionPane.showMessageDialog(null, "Personal fue creado exitosamente!");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocurrio un error probablemente con los ingresos de datos");
        }
    }//GEN-LAST:event_Button_CrearPersonalActionPerformed

    private void Button_CrearGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CrearGerenteActionPerformed
        // TODO add your handling code here:
        //String usuario, String contrasena, String Cargo, String ID, String name, int edad, String sexo, String estadoCivil, double altura, int peso
        try {
            int edad, peso;
            double altura;
            String sexo = "";
            String estado = "";
            edad = Integer.parseInt(this.label_Person_Altura.getText());
            peso = Integer.parseInt(this.label_Person_Peso.getText());
            if (this.RadioB_M.isSelected()) {
                sexo = "Masculino";
            } else {
                sexo = "Femenino";
            }
            if (this.RadioB_Casado.isSelected()) {
                estado = "Soltero";
            } else if (this.RadioB_Divorciado.isSelected()) {
                estado = "Divorciado";
            } else if (RadioB_Casado.isSelected()) {
                estado = "Casado";
            }
            altura = Double.parseDouble(this.label_Person_Altura.getText());
            Gerente x = new Gerente(this.label_Person_Usuario.getText(), this.label_Person_Password.getText(),
                    this.label_Person_Cargo.getText(), this.label_Person_ID.getText(), this.label_Person_Nombre.getText(),
                    edad, sexo, estado, altura, peso);
            contactos.add(x);
            DefaultComboBoxModel dc
                    = (DefaultComboBoxModel) this.ComboBox_Contactos.getModel();
            dc.addElement(x);
            DefaultComboBoxModel dc1
                    = (DefaultComboBoxModel) this.RM_ComboBox_Contactos.getModel();
            dc1.addElement(x);

            this.label_Person_Usuario.setText("");
            this.label_Person_Password.setText("");
            this.label_Person_Altura.setText("");
            this.label_Person_Horario.setText("");
            this.label_Person_Peso.setText("");
            this.label_Person_Altura.setText("");
            this.label_Person_Sueldo.setText("");
            this.label_Person_Ocupacion.setText("");
            this.label_Person_Horario.setText("");
            this.label_Person_ID.setText("");
            this.label_Person_Nombre.setText("");
            this.label_Person_Edad.setText("");
            this.label_Person_Cargo.setText("");
            JOptionPane.showMessageDialog(null, "Gerente fue creado exitosamente!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error probablemente con los ingresos de datos");
        }
    }//GEN-LAST:event_Button_CrearGerenteActionPerformed

    private void label_Articulos_InstruccionesFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_Articulos_InstruccionesFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_Articulos_InstruccionesFActionPerformed

    private void label_Articulos_DescripcionFigurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_Articulos_DescripcionFigurasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_Articulos_DescripcionFigurasActionPerformed

    private void label_Articulos_CasaColaboracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_Articulos_CasaColaboracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_Articulos_CasaColaboracionActionPerformed

    private void label_Articulos_TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_Articulos_TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_Articulos_TituloActionPerformed

    private void label_Person_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_Person_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_Person_NombreActionPerformed

    private void label_Person_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_Person_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_Person_IDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String emisor  = this.EM_Emisor.getText(), receptor = this.EM_Receptor.getText(), msg = this.EM_Mensaje.getText();
        String size  = EM_Mensaje.getText().toString();
        int Actualsize  = size.length();
        System.out.println(EM_Mensaje.getText().toString());
        System.out.println("Size string: "  + Actualsize);
        Message_ProgressBar.setMinimum(0);
        Message_ProgressBar.setValue(0);
        Message_ProgressBar.setMaximum(Actualsize);
        mj =new HiloMensaje(Message_ProgressBar,Table_EmuladorMensaje,emisor,receptor,msg);
        mj.start();
//        Mensaje x = new Mensaje(this.EM_Emisor.getText(), this.EM_Receptor.getText(), this.EM_Mensaje.getText());
//        this.EM_Emisor.setText("");
//        this.EM_Receptor.setText("");
//        this.EM_Mensaje.setText("");
//        if (rootPaneCheckingEnabled) {
//        mensajes.add(x);
//        Object[] newrow = {
//            x.getEmisor(),
//            x.getReceptor(),
//            x.getContenido(),};
//        DefaultTableModel modelo
//                = (DefaultTableModel) this.Table_EmuladorMensaje.getModel();
//        modelo.addRow(newrow);
//        this.Table_EmuladorMensaje.setModel(modelo);
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RM_Button_ModificarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RM_Button_ModificarPersonaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo
                = (DefaultTableModel) this.JTable_Person.getModel();
        int row = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la fila que deaseas cambiar!"));
        int column = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la columna que deaseas cambiar!"));
        String data = JOptionPane.showInputDialog(null, "Ingrese el nuevo data");
        modelo.setValueAt(data, row, column);
        JTable_Person.setModel(modelo);
    }//GEN-LAST:event_RM_Button_ModificarPersonaActionPerformed

    private void JB_ModificarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ModificarArticuloActionPerformed
        // TODO add your handling code here:
         DefaultTableModel modelo
                = (DefaultTableModel) this.JTable_Articulos.getModel();
        int row = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la fila que deaseas cambiar!"));
        int column = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la columna que deaseas cambiar!"));
        String data = JOptionPane.showInputDialog(null, "Ingrese el nuevo data");
        modelo.setValueAt(data, row, column);
        JTable_Articulos.setModel(modelo);
    }//GEN-LAST:event_JB_ModificarArticuloActionPerformed

    private void RM_ComboBox_ArticulosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RM_ComboBox_ArticulosItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == 2) {
            if (this.RM_ComboBox_Contactos.getSelectedItem() instanceof Articulos) {
                Articulos article = (Articulos) this.RM_ComboBox_Contactos.getSelectedItem();
                Object[] newrow = {
                    article.getTitulo(),
                    article.getDescripcion(),
                    article.getEditorial(),
                    article.getPuntuacion(),
                    };
                DefaultTableModel modelo
                        = (DefaultTableModel) this.JTable_Person.getModel();
                modelo.addRow(newrow);
                this.JTable_Person.setModel(modelo);
            }
        }
        
    }//GEN-LAST:event_RM_ComboBox_ArticulosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    Color color;
    ArrayList<Person> contactos = new ArrayList();
    ArrayList<Mensaje> mensajes = new ArrayList();
    ArrayList<Articulos> articulos = new ArrayList();
    HiloMensaje mj;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Color;
    private javax.swing.JButton Button_CrearComic;
    private javax.swing.JButton Button_CrearFigura;
    private javax.swing.JButton Button_CrearGerente;
    private javax.swing.JButton Button_CrearJuego;
    private javax.swing.JButton Button_CrearPersonal;
    private javax.swing.JComboBox<String> ComboBox_Contactos;
    private javax.swing.JTextField EM_Emisor;
    private javax.swing.JTextField EM_Mensaje;
    private javax.swing.JTextField EM_Receptor;
    private javax.swing.ButtonGroup EstadoCivil;
    private javax.swing.JButton JB_ModificarArticulo;
    private javax.swing.JTable JTable_Articulos;
    private javax.swing.JTable JTable_Person;
    private javax.swing.JProgressBar Message_ProgressBar;
    private javax.swing.JButton RM_Button_ModificarPersona;
    private javax.swing.JButton RM_Button_RemoveArticulo;
    private javax.swing.JButton RM_Button_RemovePerson;
    private javax.swing.JComboBox<String> RM_ComboBox_Articulos;
    private javax.swing.JComboBox<String> RM_ComboBox_Contactos;
    private javax.swing.JRadioButton RadioB_Casado;
    private javax.swing.JRadioButton RadioB_Divorciado;
    private javax.swing.JRadioButton RadioB_F;
    private javax.swing.JRadioButton RadioB_M;
    private javax.swing.JRadioButton RadioB_Soltero;
    private javax.swing.ButtonGroup Sex;
    private javax.swing.JTable Table_EmuladorMensaje;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jl_hora;
    private javax.swing.JFormattedTextField label_Articulos_Calidad;
    private javax.swing.JTextField label_Articulos_CasaColaboracion;
    private javax.swing.JTextField label_Articulos_Descripcion;
    private javax.swing.JTextField label_Articulos_DescripcionComics;
    private javax.swing.JTextField label_Articulos_DescripcionFiguras;
    private javax.swing.JTextField label_Articulos_Edicion;
    private javax.swing.JTextField label_Articulos_Editorial;
    private javax.swing.JTextField label_Articulos_InstruccionesF;
    private javax.swing.JTextField label_Articulos_Pais;
    private javax.swing.JTextField label_Articulos_Puntuacion;
    private javax.swing.JTextField label_Articulos_Tamano;
    private javax.swing.JTextField label_Articulos_TiempoGarantia;
    private javax.swing.JTextField label_Articulos_Titulo;
    private javax.swing.JTextField label_Articulos_Volumen;
    private javax.swing.JFormattedTextField label_Person_Altura;
    private javax.swing.JTextField label_Person_Cargo;
    private javax.swing.JFormattedTextField label_Person_Edad;
    private javax.swing.JTextField label_Person_Horario;
    private javax.swing.JTextField label_Person_ID;
    private javax.swing.JTextField label_Person_Nombre;
    private javax.swing.JTextField label_Person_Ocupacion;
    private javax.swing.JTextField label_Person_Password;
    private javax.swing.JFormattedTextField label_Person_Peso;
    private javax.swing.JTextField label_Person_Sueldo;
    private javax.swing.JTextField label_Person_Tiempo;
    private javax.swing.JTextField label_Person_Usuario;
    // End of variables declaration//GEN-END:variables
}
